package com.openclaw.android

import android.content.Context
import com.openclaw.android.core.env.EnvironmentConfig
import com.openclaw.android.core.env.EnvironmentResolver
import java.io.File

/**
 * EnvironmentBuilder — compatibility shim.
 *
 * Delegates to [EnvironmentResolver] (new module) while keeping the
 * existing public API intact so all callers continue to compile.
 *
 * New code should use EnvironmentResolver directly.
 */
object EnvironmentBuilder {

    fun build(context: Context): Map<String, String> =
        buildEnvironment(context.filesDir, context.packageName)

    /** Legacy alias — used by CommandRunner and tests. */
    fun buildTermuxEnvironment(context: Context? = null): Map<String, String> =
        if (context != null) build(context)
        else buildEnvironment(null)

    fun buildEnvironment(filesDir: File?, packageName: String? = null): Map<String, String> {
        val actualFilesDir = filesDir ?: resolveFilesDirFromEnv() ?: File("/data/local/tmp")
        val actualPackageName = packageName
            ?: actualFilesDir.parentFile?.name
            ?: "com.openclaw.android"
        val config = EnvironmentResolver.resolve(actualFilesDir)
        EnvironmentResolver.ensureResolvConf(config)
        generateDynamicWrappers(config)
        return EnvironmentResolver.buildEnvMap(config, actualPackageName)
    }

    /** Detect payload directory (prioritizing HOME for the new layout). */
    fun resolvePayloadDir(filesDir: File): File =
        EnvironmentResolver.resolvePayloadDir(filesDir)

    /** Detect prefix directory (payload or legacy /usr). */
    fun resolvePrefix(filesDir: File): File =
        EnvironmentResolver.resolve(filesDir).prefix

    fun resolveActivePaths(filesDir: File? = null): Pair<String, String> {
        val actualFilesDir = filesDir ?: resolveFilesDirFromEnv() ?: File("/data/local/tmp")
        val config = EnvironmentResolver.resolve(actualFilesDir)
        return Pair(config.prefix.absolutePath, config.homeDir.absolutePath)
    }

    // ── Private helpers ────────────────────────────────────────────────────

    private fun resolveFilesDirFromEnv(): File? {
        val home = System.getenv("HOME") ?: return null
        val homeFile = File(home)
        return if (homeFile.name == "home") homeFile.parentFile else null
    }

    /**
     * Generate glibc-wrapped binary wrappers in .openclaw-android/bin/.
     * Called as a side effect of buildEnvironment to ensure wrappers are
     * always up-to-date on every launch.
     */
    private fun generateDynamicWrappers(config: EnvironmentConfig) {
        val loader = config.linker
        if (!loader.exists()) return

        val ocaBinDir = File(config.ocaDir, "bin").also { it.mkdirs() }
        val glibcLibDir = config.glibcLib

        val binaries = listOf("bash", "node", "npm", "git", "openclaw")
        for (binName in binaries) {
            val realBin = File(config.prefix, "bin/$binName")
            if (!realBin.exists()) continue
            val wrapperFile = File(ocaBinDir, binName)
            try {
                val content = buildString {
                    appendLine("#!/system/bin/sh")
                    appendLine("# glibc-wrapped $binName — auto-generated by EnvironmentBuilder")
                    appendLine("unset LD_PRELOAD")
                    appendLine("export LD_LIBRARY_PATH=\"${glibcLibDir.absolutePath}:\${LD_LIBRARY_PATH}\"")
                    appendLine("exec \"${loader.absolutePath}\" --library-path \"${glibcLibDir.absolutePath}\" \"${realBin.absolutePath}\" \"\$@\"")
                }
                wrapperFile.writeText(content)
                wrapperFile.setExecutable(true, false)
            } catch (_: Exception) {}
        }
    }
}
