package com.openclaw.android.core.install

import com.openclaw.android.AppLogger
import com.openclaw.android.core.env.EnvironmentConfig
import java.io.File

/**
 * ScriptWriter — generates shell scripts for launching OpenClaw.
 *
 * All scripts use the glibc dynamic linker directly — never /system/bin/sh
 * to invoke node, which would fail with "bad ELF magic" or glibc errors.
 *
 * Generated scripts:
 *   - openclaw-start.sh: main gateway launcher (homeDir)
 *   - node wrapper: glibc-wrapped node in .openclaw-android/bin/
 *   - npm wrapper: delegates to node + npm-cli.js
 */
object ScriptWriter {

    private const val TAG = "ScriptWriter"

    /**
     * Create the main openclaw-start.sh launcher in homeDir.
     *
     * Uses run-openclaw.sh from the payload if it exists (preferred),
     * otherwise generates a direct launcher using the glibc linker.
     *
     * Critical env vars set in the script:
     *   - unset LD_PRELOAD: prevents bionic libtermux-exec.so injection
     *   - OA_GLIBC=1: signals to OpenClaw that glibc mode is active
     *   - CONTAINER=1: disables features that require systemd
     */
    fun writeGatewayScript(config: EnvironmentConfig): Boolean {
        val startScript = File(config.homeDir, "openclaw-start.sh")
        val runScript = File(config.payloadDir, "run-openclaw.sh")

        val content = if (runScript.exists()) {
            runScript.setExecutable(true, false)
            buildString {
                appendLine("#!/system/bin/sh")
                appendLine("# OpenClaw gateway launcher — generated by ScriptWriter")
                appendLine("export HOME=\"${config.homeDir.absolutePath}\"")
                appendLine("export TMPDIR=\"${config.tmpDir.absolutePath}\"")
                appendLine("export OA_GLIBC=1")
                appendLine("export CONTAINER=1")
                appendLine("# CRITICAL: remove LD_PRELOAD to prevent bionic crash in glibc process")
                appendLine("unset LD_PRELOAD")
                appendLine("exec \"${runScript.absolutePath}\" gateway --host 0.0.0.0 \"\$@\"")
            }
        } else {
            buildDirectLaunchScript(config)
        }

        return try {
            startScript.parentFile?.mkdirs()
            startScript.writeText(content)
            startScript.setExecutable(true, false)
            AppLogger.i(TAG, "Gateway script written: ${startScript.absolutePath}")
            true
        } catch (e: Exception) {
            AppLogger.e(TAG, "Failed to write gateway script: ${e.message}", e)
            false
        }
    }

    /**
     * Create the node wrapper in .openclaw-android/bin/node.
     *
     * The wrapper invokes node via the glibc dynamic linker:
     *   ld-linux-aarch64.so.1 --library-path <glibcLib> <node.real> [args...]
     *
     * This is the pattern documented in OPENCLAW_ANDROID_FINAL.md §3.
     */
    fun writeNodeWrapper(config: EnvironmentConfig): Boolean {
        val binDir = File(config.ocaDir, "bin").also { it.mkdirs() }
        val nodeWrapper = File(binDir, "node")

        if (!config.nodeBin.exists()) {
            AppLogger.w(TAG, "node binary not found at ${config.nodeBin.absolutePath}")
            return false
        }
        config.nodeBin.setExecutable(true, false)

        val compatJs = File(config.ocaDir, "patches/glibc-compat.js")

        val content = buildString {
            appendLine("#!/system/bin/sh")
            appendLine("# OpenClaw glibc-wrapped Node.js — auto-generated by ScriptWriter")
            appendLine("# DO NOT invoke node directly — use this wrapper")
            appendLine("unset LD_PRELOAD")
            appendLine("export _OA_WRAPPER_PATH=\"${nodeWrapper.absolutePath}\"")
            if (compatJs.exists()) {
                appendLine("_OA_COMPAT=\"${compatJs.absolutePath}\"")
                appendLine("if [ -f \"\$_OA_COMPAT\" ]; then")
                appendLine("  case \"\${NODE_OPTIONS:-}\" in")
                appendLine("    *\"\$_OA_COMPAT\"*) ;;")
                appendLine("    *) export NODE_OPTIONS=\"\${NODE_OPTIONS:+\$NODE_OPTIONS }-r \$_OA_COMPAT\" ;;")
                appendLine("  esac")
                appendLine("fi")
            }
            if (config.isGlibcReady) {
                appendLine("exec \"${config.linker.absolutePath}\" \\")
                appendLine("  --library-path \"${config.glibcLib.absolutePath}\" \\")
                appendLine("  \"${config.nodeBin.absolutePath}\" \"\$@\"")
            } else {
                // Fallback: direct execution (may work on some devices)
                appendLine("exec \"${config.nodeBin.absolutePath}\" \"\$@\"")
            }
        }

        return try {
            nodeWrapper.writeText(content)
            nodeWrapper.setExecutable(true, false)
            AppLogger.i(TAG, "node wrapper written: ${nodeWrapper.absolutePath}")
            true
        } catch (e: Exception) {
            AppLogger.e(TAG, "Failed to write node wrapper: ${e.message}", e)
            false
        }
    }

    /**
     * Create the npm wrapper in .openclaw-android/bin/npm.
     */
    fun writeNpmWrapper(config: EnvironmentConfig): Boolean {
        val binDir = File(config.ocaDir, "bin").also { it.mkdirs() }
        val nodeWrapper = File(binDir, "node")
        val npmCli = listOf(
            File(config.payloadDir, "glibc/lib/node_modules/npm/bin/npm-cli.js"),
            File(config.prefix, "lib/node_modules/npm/bin/npm-cli.js"),
        ).firstOrNull { it.exists() } ?: return false

        val npmWrapper = File(binDir, "npm")
        return try {
            npmWrapper.writeText(
                "#!/system/bin/sh\nexec \"${nodeWrapper.absolutePath}\" \"${npmCli.absolutePath}\" \"\$@\"\n"
            )
            npmWrapper.setExecutable(true, false)
            AppLogger.i(TAG, "npm wrapper written: ${npmWrapper.absolutePath}")
            true
        } catch (e: Exception) {
            AppLogger.e(TAG, "Failed to write npm wrapper: ${e.message}", e)
            false
        }
    }

    /**
     * Write installed.json marker with version info.
     */
    fun writeInstalledMarker(
        config: EnvironmentConfig,
        openclawVersion: String,
        nodeVersion: String,
        source: String = "payload",
    ): Boolean {
        val marker = File(config.ocaDir, "installed.json")
        return try {
            config.ocaDir.mkdirs()
            marker.writeText(
                """
                {
                  "installed": true,
                  "source": "$source",
                  "openclawVersion": "$openclawVersion",
                  "nodeVersion": "$nodeVersion",
                  "payloadDir": "${config.payloadDir.absolutePath}",
                  "installedAt": ${System.currentTimeMillis()}
                }
                """.trimIndent()
            )
            AppLogger.i(TAG, "installed.json written: openclaw=$openclawVersion node=$nodeVersion")
            true
        } catch (e: Exception) {
            AppLogger.e(TAG, "Failed to write installed.json: ${e.message}", e)
            false
        }
    }

    // ── Private helpers ────────────────────────────────────────────────────

    private fun buildDirectLaunchScript(config: EnvironmentConfig): String {
        val nodeWrapper = File(config.ocaDir, "bin/node")
        val ocMjs = config.openClawMjs

        return buildString {
            appendLine("#!/system/bin/sh")
            appendLine("# OpenClaw direct gateway launcher — generated by ScriptWriter")
            appendLine("export HOME=\"${config.homeDir.absolutePath}\"")
            appendLine("export TMPDIR=\"${config.tmpDir.absolutePath}\"")
            appendLine("export LD_LIBRARY_PATH=\"${config.glibcLib.absolutePath}\"")
            appendLine("export OA_GLIBC=1")
            appendLine("export CONTAINER=1")
            appendLine("export CLAWDHUB_WORKDIR=\"${config.homeDir.absolutePath}/.openclaw/workspace\"")
            if (config.certPem.exists()) {
                appendLine("export SSL_CERT_FILE=\"${config.certPem.absolutePath}\"")
                appendLine("export CURL_CA_BUNDLE=\"${config.certPem.absolutePath}\"")
            }
            appendLine("# CRITICAL: remove LD_PRELOAD to prevent bionic crash in glibc process")
            appendLine("unset LD_PRELOAD")
            appendLine()
            if (nodeWrapper.exists()) {
                appendLine("exec \"${nodeWrapper.absolutePath}\" \"${ocMjs.absolutePath}\" gateway --host 0.0.0.0 \"\$@\"")
            } else if (config.isGlibcReady && config.isNodeReady) {
                appendLine("exec \"${config.linker.absolutePath}\" \\")
                appendLine("  --library-path \"${config.glibcLib.absolutePath}\" \\")
                appendLine("  \"${config.nodeBin.absolutePath}\" \\")
                appendLine("  \"${ocMjs.absolutePath}\" gateway --host 0.0.0.0 \"\$@\"")
            } else {
                appendLine("echo 'ERROR: OpenClaw environment not ready. Run setup first.' >&2")
                appendLine("exit 1")
            }
        }
    }
}
