#!/usr/bin/env bash
# openclaw-shim.sh — Write the version-pin guard at $PREFIX/bin/openclaw
#
# OpenClaw can replace itself (`openclaw update`, `openclaw --update`) with the
# latest npm release, which may require a newer Node.js than the pinned one and
# then refuses to start. The guard blocks those commands and passes everything
# else through to openclaw.mjs.
#
# `npm install -g openclaw` (and our npm wrapper) rewrite $PREFIX/bin/openclaw,
# so run this after every OpenClaw install (install.sh, update.sh, post-setup.sh).
# $PREFIX/bin is the one directory present in every PATH we launch from
# (Termux shell, app terminal, boot auto-start, app EnvironmentBuilder).
set -euo pipefail

: "${PREFIX:?PREFIX not set}"
: "${HOME:?HOME not set}"

OC_BIN="$PREFIX/bin/openclaw"
OC_MJS="$PREFIX/lib/node_modules/openclaw/openclaw.mjs"
OC_NODE="$HOME/.openclaw-android/bin/node"
[ -x "$OC_NODE" ] || OC_NODE="node"

if [ ! -f "$OC_MJS" ]; then
    echo -e "\033[1;33m[WARN]\033[0m openclaw.mjs not found — version guard not installed"
    exit 0
fi

OC_TMP="$OC_BIN.tmp.$$"
trap 'rm -f "$OC_TMP"' EXIT
cat > "$OC_TMP" << SHIM
#!$PREFIX/bin/bash
# openclaw — OpenClaw on Android version-pin guard.
# Generated by platforms/openclaw/openclaw-shim.sh; rewritten on every install/update.
# Blocks OpenClaw self-update; all other commands pass through unchanged.
_oa_block=false
for _oa_arg in "\$@"; do
    [ "\$_oa_arg" = "--update" ] && _oa_block=true && break
done
if [ "\$_oa_block" = false ]; then
    # Find the subcommand: skip global flags (and the values of those that take one).
    _oa_skip=false
    _oa_next=false
    for _oa_arg in "\$@"; do
        if [ "\$_oa_next" = true ]; then
            # Only the read-only "update status" is allowed through.
            [ "\$_oa_arg" = "status" ] && _oa_block=false
            break
        fi
        if [ "\$_oa_skip" = true ]; then _oa_skip=false; continue; fi
        case "\$_oa_arg" in
            --profile|--container|--log-level) _oa_skip=true ;;
            -*) ;;
            update) _oa_block=true; _oa_next=true ;;
            *) break ;;
        esac
    done
fi
if [ "\$_oa_block" = true ]; then
    echo "[BLOCKED] OpenClaw is pinned to the version verified by OpenClaw on Android." >&2
    echo "          Run 'oa --update' to update safely. ('openclaw update status' is allowed.)" >&2
    exit 1
fi
if [ ! -f "$OC_MJS" ]; then
    echo "[FAIL] OpenClaw is not installed ($OC_MJS missing). Run 'oa --update'." >&2
    exit 127
fi
exec "$OC_NODE" "$OC_MJS" "\$@"
SHIM
chmod +x "$OC_TMP"
# rename(2) replaces the npm symlink itself, never the file it points to
mv -f "$OC_TMP" "$OC_BIN"
echo -e "\033[0;32m[OK]\033[0m   openclaw version guard installed ($OC_BIN)"
